"""add debts and debt_history

Revision ID: f7425d63180c
Revises: ef234c144f9c
Create Date: 2026-07-21 03:35:41.584797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7425d63180c'
down_revision: Union[str, None] = 'ef234c144f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('counterparty_phone', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('owed', 'paid', name='debt_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_created_at'), 'debts', ['created_at'], unique=False)
    op.create_index(op.f('ix_debts_user_id'), 'debts', ['user_id'], unique=False)
    op.create_table('debt_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('field_changed', sa.Enum('amount', 'status', name='debt_field_changed'), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_history_changed_at'), 'debt_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_debt_history_debt_id'), 'debt_history', ['debt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_history_debt_id'), table_name='debt_history')
    op.drop_index(op.f('ix_debt_history_changed_at'), table_name='debt_history')
    op.drop_table('debt_history')
    op.drop_index(op.f('ix_debts_user_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_created_at'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###
